# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # If no nodePort is specified, Kubernetes will assign one automatically.
      # You can optionally specify a port in the allowed range (typically between 30000-32767):
      nodePort: 30080
